# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
