# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 19:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170922_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
